# Generated by Django 5.1.3 on 2024-11-26 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="icon",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
